//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustonLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int CostId { get; set; }
        public System.DateTime Date { get; set; }
        public string CostBy { get; set; }
        public string TypeOfCost { get; set; }
        public int CostAmount { get; set; }
    }
}
