//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustonLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public int CustomerPaymentId { get; set; }
        public int CustomerId { get; set; }
        public int TotalPreviousDue { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Payment { get; set; }
        public int Due { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
