//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustonLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerPayment
    {
        public int WorkerPaymentId { get; set; }
        public int WorkerId { get; set; }
        public int PayableAmount { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Payment { get; set; }
        public int RepayableAmount { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
